apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: DeliveryManagement
  description: ${{ values.description }}
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.destination.owner}}
  definition:
    $text: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}/blob/master/DeliveryManagement/DeliveryManagement/src/main/resources/api-docs.yaml
